### PR TITLE
Fix Dialogflow Messenger client in sample chat app

### LINKED ISSUE #235: Breaking Bug in Sample App: Conversation Web App
## Bug report

The chat widget on https://vertex-ai-conversation.web.app/ does not work.

404 on https://www.gstatic.com/dialogflow-console/fast/messenger-cx/prod/df-messenger.min.js?v=1

also `Uncaught TypeError: Cannot read properties of null (reading 'querySelector')` but that's perhaps due to the missing JS file above.

### PR DESCRIPTION
**Pull request by koverholt**
Fixes #235.

- Fix link to DF Messenger JS client
- Add project ID to DF Messenger options
- Fix formatting/linting w/ prettier

Fixed version of site has already been deployed to https://vertex-ai-conversation.web.app/.

### CODE REVIEW

File: conversation/chat-app/src/routes/+page.svelte [hunk 1]
```diff
@@ -119,8 +121,9 @@
       </div>
       <div class="m-12 w-2/5">
         <script
-          src="https://www.gstatic.com/dialogflow-console/fast/messenger-cx/prod/df-messenger.min.js?v=1"></script>
+          src="https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/df-messenger.js"></script>
         <df-messenger
+          project-id="koverholt-devrel-355716"
```
Comment (holtskinner) [inline conversation/chat-app/src/routes/+page.svelte:126]: Is there a way you can pass this in a config from the backend instead of hardcoding it in the repo?
Although, it does look like the published website has this value in the source code too 😅

(At least replace with a placeholder here so it's not published)

**Review by holtskinner — APPROVED** [review]

File: conversation/chat-app/src/routes/+page.svelte [hunk 2]
```diff
@@ -62,7 +62,10 @@
 
 <Navbar let:hidden let:toggle class="bg-[#B1D6FC]">
   <NavBrand href="/">
-    <img src="vertex-ai-conversation-logo.png" class="mr-3 h-6 sm:h-9" alt="Vertex AI Conversation" />
+    <img
+      src="vertex-ai-conversation-logo.png"
```
Comment (holtskinner) [inline conversation/chat-app/src/routes/+page.svelte:66]: nit: Out of scope for this CL, but the product isn't using this logo anymore.

You can replace with this link to the Vertex AI logo https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/web-24dp/colors_vertexai_color_1x_web_24dp.png

File: conversation/chat-app/src/routes/+page.svelte (hunk 1 above)
Comment (koverholt) [reply conversation/chat-app/src/routes/+page.svelte]: Good point, I should be consistent with the values in https://github.com/GoogleCloudPlatform/generative-ai/blob/main/conversation/chat-app/.firebaserc and https://github.com/GoogleCloudPlatform/generative-ai/blob/main/conversation/chat-app/firebase.json. Fixed in bdd3388.

File: conversation/chat-app/src/routes/+page.svelte (hunk 2 above)
Comment (koverholt) [reply conversation/chat-app/src/routes/+page.svelte]: Excellent, thanks for pointing that out. I updated the favicon, logo in the top navbar, and logo(s) in the diagram.
